#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np


---
# A zoo of matrices
---


In [2]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 0.15090163  0.12378599 -1.04631822  0.74424817  0.06249143]
 [-0.3576683   0.30022496 -0.31949075 -0.39401028  1.90472818]
 [-1.67801182  2.01914964  0.9939216   0.27417423  0.54553794]
 [ 0.74401542  2.09354696 -2.43228202  0.23339571  1.44346137]
 [-2.18559858  0.45458289 -0.46746504  0.32758599  1.67313008]]
 
[[ 0.10711943  1.76913956]
 [-0.75862569  0.21636823]
 [-1.62953774  0.7085451 ]
 [ 0.32045638  1.32723457]
 [ 0.42810319 -0.03572253]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 0.82138908  0.          0.          0.          0.        ]
 [ 1.1554026   1.0339661   0.          0.          0.        ]
 [ 0.25183118 -1.14661004 -0.92486022  0.          0.        ]
 [ 0.37031559 -1.00864077 -1.33736397  0.10303075  0.        ]
 [ 0.95041179 -1.16251356 -0.10884254  2.4738073  -1.81824867]]
 


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

---
# Matrix vector products
---


Let's see how we can multiply matrix by vector 

![](./images/img.png)

To do such operation vector should have same number of rows as matrix columns. And then we do such operation, the result will be new vector.

![](./images/img_1.png)


---
# Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

ValueError: operands could not be broadcast together with shapes (5,4) (5,3) 


---
# Matrix-scalar multiplication
---


In [4]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# Transpose

In [2]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [3]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(C.conjugate().T) # note the sign flips!
# Another note: the code I used in the video will soon be depreciated; use the above line instead.


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# Diagonal and trace
---


In [5]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[ 1. -0. -6.  3.]
 [-2.  2.  1.  3.]
 [-2. -8. -1. -2.]
 [ 8. -2.  1. -7.]]
 
[ 1.  2. -1. -7.]
[[ 1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -7.]]
-5.0 -5.0



---
# Broadcasting matrix arithmetic
---


In [2]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [3]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
print(A+c)
# print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 