# Content

[A zoo of matrices](#-a-zoo-of-matrices)

[Matrix vector products](#-matrix-vector-products)

[Matrix Null space and calculation of Null space](#-matrix-null-space-and-calculation-of-null-space)

[Matrix Column space](#-matrix-column-space)

[Eigenvectors and Eigenspaces](#-linear-transformation-of-vectors-using-matrices)

[Eigenvectors and Eigenspaces](#-expressing-a-projection-on-to-a-line-as-a-matrix-vector-product)

[Eigenvectors and Eigenspaces](#-matrix-product)

[Eigenvectors and Eigenspaces](#-matrix-addition-and-subtraction)

#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [3]:
import numpy as np


---
# A zoo of matrices
---


In [2]:

# square vs. rectangular
S = np.random.randn(5, 5)
R = np.random.randn(5, 2)  # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4, 4))
print(Z), print(' ')

# diagonal
D = np.diag([1, 2, 3, 5, 2])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5, 5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3, 2)
B = np.random.randn(4, 4)
C = np.concatenate((A, B), axis=1)
print(C)

[[ 2.35058224 -0.40154064  0.29942109  0.17430237 -1.68468147]
 [-0.00522525  1.49173626 -0.51802445  1.18796797 -1.05011861]
 [-0.89326073  0.56870057  1.00700629  0.16466154  0.1449396 ]
 [-0.09513841  0.32819056 -2.00521275 -1.80077252 -1.67958604]
 [-0.28740774 -1.12150286 -0.78525631  0.76449827  0.2755754 ]]
 
[[ 0.24653541 -0.87537577]
 [-0.78511682 -0.37380959]
 [ 0.0235158  -0.14353341]
 [-0.3373425  -0.13045002]
 [-0.15309596 -0.14388752]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[-1.8014022   0.          0.          0.          0.        ]
 [ 1.31427426  1.83728585  0.          0.          0.        ]
 [ 0.36624841  0.99919651  1.28934116  0.          0.        ]
 [-1.5703047  -0.16265934 -0.05542943 -1.82038286  0.        ]
 [ 0.9532183   0.2781282   0.09059743  0.39030282 -0.88451616]]
 


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

---
# Matrix vector products
---


Let's see how we can multiply matrix by vector 

![](./images/img.png)

To do such operation vector should have same number of rows as matrix columns. And then we do such operation, the result will be new vector.

![](./images/img_1.png)

In [4]:
# Example 

matrix = [[1, 2, 3],
          [4, 5, 6]]

vector = [1, 2, 3]

result = [1*1 + 2*2 + 3*3, 4*1 + 4*2 + 4*3]

result

[14, 24]

---
# Matrix null space and calculation of null space
---

The null space of matrix is the set of vectors. And when we multiply it times matrix we receive 0 vector. 

matrix = [[1, 2, 3, ... n],
          [4, 5, 6, ... n]]

vector = [x1, x2, x3, ... xn]

matrix * vector = [0, 0, ... 0]

In general, it will look like this 

## Calculating the Null Space of a Matrix

To calculate the null space (or kernel) of a matrix, you need to find all the vectors that satisfy the equation A*X = R, where A is the given matrix and R is the zero vector. Here is a detailed explanation of how to do this:

### Step-by-Step Process

1. **Write the Matrix Equation**:
   Suppose \( A \) is an \( m \times n \) matrix. The null space consists of all vectors \( \mathbf{x} \in \mathbb{R}^n \) such that:
   \[
   A\mathbf{x} = \mathbf{0}
   \]

2. **Set Up the Augmented Matrix**:
   Form the augmented matrix \([A | \mathbf{0}]\), where \(\mathbf{0}\) is a zero column vector of appropriate dimension.

3. **Row Reduce to Row Echelon Form (REF)**:
   Use Gaussian elimination to row reduce the augmented matrix to its row echelon form. This involves performing a series of row operations to simplify the matrix:
   - Swap rows.
   - Multiply rows by non-zero scalars.
   - Add or subtract multiples of rows from each other.

4. **Identify Pivot Columns**:
   In the row echelon form of the matrix, identify the pivot columns. These columns contain the leading entries (first non-zero entry from the left) in each row.

5. **Determine Free Variables**:
   The variables corresponding to the pivot columns are the basic variables, and the variables corresponding to the non-pivot columns are the free variables. Free variables can take any value.

6. **Express Basic Variables in Terms of Free Variables**:
   Solve the system of linear equations for the basic variables in terms of the free variables. This step involves back-substitution if necessary.

7. **Form the General Solution**:
   Express the general solution as a linear combination of vectors. Each free variable corresponds to a vector in the null space. The null space is the span of these vectors.


### Example:

Example

![](./images/img_2.png)

![](./images/img_3.png)

![](./images/img_4.png)

![](./images/img_5.png)

![](./images/img_6.png)

![](./images/img_7.png)

![](./images/img_8.png)

### Dimension of the Null Space (Rank) 

It is a number of elements in a basis for the subspace, so for example above it is 2.

### Nullity of the Null Space 

It is the number of not pivot columns, so for example above it is 2.

### Relation to linear independence

If matrix Null space contains only zero vector, it means that all vectors in matrix are linearly independent.


---
# Matrix column space
---

The column space of a matrix, also known as the range or image, is the set of all possible linear combinations of its column vectors. In simpler terms, it is the span of the columns of the matrix.


---
# Linear transformation of vectors using matrices
---

Here us general representation for 2D space 

![](./images/img_9.png)

For example if we have such space with two basis vectors green [1, 0] and red [0, 1]  

![](./images/img_10.png)

Then we apply some transformation where green becomes [1, -2], and red [3, 0]

![](./images/img_11.png)

So to represent all other vectors which depends on green and red basis we should just use method above.

---
# Expressing a Projection on to a line as a Matrix Vector product.
---

![](./images/img_12.png)

![](./images/img_13.png)

![](./images/img_14.png)


---
# Matrix product
---

https://www.mathsisfun.com/algebra/matrix-multiplying.html


---
# Matrix addition and subtraction
---


In [4]:

# create random matrices
A = np.random.randn(5, 4)
B = np.random.randn(5, 3)
C = np.random.randn(5, 4)

# try to add them
# A + B # will be error because of 5x4 matrix can not be added to 5x3
A + C 

# "shifting" a matrix
l = .03  # lambda
N = 5  # size of square matrix
D = np.random.randn(N, N)  # can only shift a square matrix

Ds = D + l * np.eye(N)
print(D), print(' '), print(Ds)

[[ 0.4133893   0.6777795   0.69210947  0.61558148  1.45966855]
 [ 1.20532356 -0.39421186 -1.66922713 -0.33701723  1.09002399]
 [ 1.5909845  -0.0347962  -0.54489463 -1.00695566 -0.50006721]
 [ 0.75169649  0.0845031   0.01217283 -1.23470959 -0.02118112]
 [ 0.23258404  0.22002119  0.09224822  0.24265218  1.24716761]]
 
[[ 0.4433893   0.6777795   0.69210947  0.61558148  1.45966855]
 [ 1.20532356 -0.36421186 -1.66922713 -0.33701723  1.09002399]
 [ 1.5909845  -0.0347962  -0.51489463 -1.00695566 -0.50006721]
 [ 0.75169649  0.0845031   0.01217283 -1.20470959 -0.02118112]
 [ 0.23258404  0.22002119  0.09224822  0.24265218  1.27716761]]


(None, None, None)


---
# Matrix-scalar multiplication
---


In [4]:
# define matrix and scalar
M = np.array([[1, 2], [2, 5]])
s = 2

# pre- and post-multiplication is the same:
print(M * s)
print(s * M)


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# Transpose

In [2]:
M = np.array([[1, 2, 3],
              [2, 3, 4]])

print(M), print('')
print(M.T), print('')  # one transpose
print(M.T.T), print('')  # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [3]:
# warning! be careful when using complex matrices
C = np.array([[4 + 1j, 3, 2 - 4j]])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(C.conjugate().T)  # note the sign flips!
# Another note: the code I used in the video will soon be depreciated; use the above line instead.


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# Diagonal and trace
---


In [8]:

M = np.round(6 * np.random.randn(4, 4))
print("M: ", M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M)  # input is matrix, output is vector
D = np.diag(d)  # input is vector, output is matrix
print("d: ", d)
print("D: ", D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum(np.diag(M))
print("\ntr, tr2: ", tr, tr2)

M:  [[  1.  -6.  -3.   4.]
 [ -4.  -4.  -0.  -2.]
 [  7.  11.   9.  -3.]
 [ -0.   3. -10.  -4.]]
 
d:  [ 1. -4.  9. -4.]
D:  [[ 1.  0.  0.  0.]
 [ 0. -4.  0.  0.]
 [ 0.  0.  9.  0.]
 [ 0.  0.  0. -4.]]

tr, tr2:  2.0 2.0
