#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [2]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.04890502  0.43843011 -0.39406956 -0.61091296 -0.52427982]
 [-1.81899448 -0.15139564 -0.3724226  -0.25531734  2.35446194]
 [-0.1855171  -2.00221482 -0.24161943 -1.13213879 -0.49609362]
 [ 0.31284611  0.9128278   0.78802553  1.6397386  -0.12838545]
 [-1.68500255  2.59867386  0.42788922  0.31113882 -0.56180789]]
 
[[ 0.20165155  0.86207251]
 [-0.6627482  -0.05375612]
 [-0.69657734 -0.24408983]
 [ 0.46242996 -1.09405151]
 [-1.59006184 -0.08258198]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[-0.81379398  0.          0.          0.          0.        ]
 [ 0.58403703  1.07838399  0.          0.          0.        ]
 [ 0.82345488  1.18100457 -0.39940335  0.          0.        ]
 [-1.09649581  0.51686768  2.22205131  0.68718804  0.        ]
 [-0.20746038 -0.75110212 -1.3476184  -0.32061803 -0.47132268]]
 


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


---
# VIDEO: Matrix addition and subtraction
---


In [ ]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)


---
# VIDEO: Matrix-scalar multiplication
---


In [ ]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


# VIDEO: Transpose

In [ ]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

In [ ]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(C.conjugate().T) # note the sign flips!
# Another note: the code I used in the video will soon be depreciated; use the above line instead.



---
# VIDEO: Diagonal and trace
---


In [ ]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)


---
# VIDEO: Broadcasting matrix arithmetic
---


In [ ]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

In [ ]:
# broadcast on the rows
# print(A+r), print(' ')

# broadcast on the columns
print(A+c)
# print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors
